### ISSUE TITLE
Provide examples for all types of controllers

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#12]
- [x] [standard controller](https://book.kubebuilder.io/basics/what_is_the_controller_manager.html): coverd by [controller-rs](https://github.com/clux/controller-rs) (uses in Controller<T> from #148), `configmapgen_controller` example also exists
- [x] [finalizer controller](https://book.kubebuilder.io/beyond_basics/using_finalizers.html) - was blocked by #291 , and easier path in #475 - we now have [an example for it](https://github.com/kube-rs/kube-rs/blob/master/examples/secret_syncer.rs)
- ~~[initializer controller](https://medium.com/ibm-cloud/kubernetes-initializers-deep-dive-and-tutorial-3bc416e4e13e)~~ these are deprecated
- [x] [admission controllers](https://kubernetes.io/blog/2019/03/21/a-guide-to-kubernetes-admission-controllers/) - doable now with #484, see `admission_controller` example

**Comment by clux** [comment]
Started writing a finalizer controller the other day as an experiment. Will add it as an example later on, but the key logic here is just an Informer on the object you put the finalizer annotation on, and checking if its `object.metadata.deletion_timestamp` is a `Some`.

Might be worth adding a helper so mutate the finalizer list (an impl on ObjectMeta perhaps), but will sort that out once the example is being converted

**Comment by clux** [comment]
Going to close this. The last; finalizer is now a lot easier with the last finalizer helper prs, and there's an [example for it](https://github.com/kube-rs/kube-rs/blob/master/examples/secret_syncer.rs).
