### ISSUE TITLE
builders for kube-runtime reflector

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#276]
Trying to propagate `kube-runtime` to all external repo actix examples and noticing a few things that should be made better for a smoother experience:

- users need to import `watcher` when using `reflector` (even if they expose the same events and they only use one)
- users need to import `Writer` when using `reflector` (even though they cannot really use it sensibly)

Proposed solutions:
- [ ] add builder `Cache<T>` around `reflector` - #698 
- [ ] `Cache` builder to allow retrieving a reader as in `Controller` - #698
- [ ] add `Watcher<T>` builder - #703 

Edit: crossing out a few from feedback.
Edit2: removing ancient comments here, as a long time has passed here.

**Comment by teozkr** [comment]
> users now need to import ListParams when using reflector/watcher even if they're using defaults

They can also call it as `Default::default()`.

> - reflector exposes the Writer even if it's unsafe to have multiple writers

The `reflector` takes the `Writer` by-move, so you can't pass the same `Writer` to multiple `reflector`s.

**Comment by clux** [comment]
Ahh. Ok. Thanks. Probably going to ignore those parts then.

**Comment by clux** [comment]
Wrote some docs for the `Controller`, and that's probably the hardest one. Needed a few more dev-dependencies we already had in Cargo.lock.

https://docs.rs/kube-runtime/0.37.0/kube_runtime/controller/struct.Controller.html

**Comment by clux** [comment]
Most of the issues here are now in separate issues. So the only question left here is whether or not to add builders to `reflector`, `watcher`. This forces one question:

- if `Watcher<K>` is just a builder to call `watcher`
- and `Reflector<K>` is just a builder to call `reflector` (hiding the watcher arg + import)
- then `Controller<K>` should really just call out to `controller` (i.e. keep the original name of `controller` rather than `applier`)

**Comment by clux** [comment]
Managed to get around this with an easier solution in #907 thanks to Teo's ideas on WatchStreamExt.
