### ISSUE TITLE
minimum supported rust version policy

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#668]
Moving towards stability land (#508), we ~~should probably~~ *could* do a best effort to maintain builds on the last few stable versions of rust. (Originally discussed briefly in #665).

Problems:
- need to restrict dependency updates to upstream policies of their MSRV (which is hard with our dependency tree, but presumably it is automated if people set the `rust-version`)
- need CI to validate that our MSRV is building on that version
- people suggest a 6 month policy, but it's undoubtedly going to put a strain on maintainers

We just merged in edition 2021 so there's limits to how much we can do (and the 2021 release is incidentally the release that supports `rust-version` key. For now we could follow this general plan:

- [x] set [rust-version](https://doc.rust-lang.org/cargo/reference/manifest.html#the-rust-version-field) to `1.56` in all `Cargo.toml`s (https://github.com/kube-rs/kube-rs/commit/7a265b9d7c0e0200f5dc7237d04ddab453a2ce00)
- [x] add [badge below](https://github.com/kube-rs/kube-rs/issues/668#issuecomment-952219250) - #680
- [ ] add CI to run against 1.56 (with a sanity check that the rust version matches what we set in `Cargo.toml`s) - #687
- [ ] run that ci job ~~daily~~ pre-merge - #687

and then maybe in the futere (depending on need, and what type of problems we run into):

- speculatively commit to 3 months initially (that's 2 stable rust releases back)
- write a speculative policy document somewhere (e.g. something like [wg/msrv](https://github.com/rust-embedded/wg/blob/master/ops/msrv.md))

but that will be one for a later issue.
