### ISSUE TITLE
Tracking issue for stable tooling

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#707]
As noted in the [contributing guide](./CONTRIBUTING.md)  we use **nightly ci tooling** for `rustfmt` and `rustdoc` for a few features not available on **stable**. This issue lists the nightly features we use in the hope that one day we can just use stable for everything.

This is a developer workflow ergonomics issue, all our published crates work on stable.

### rustdoc
- [ ] [`doc_cfg`](https://doc.rust-lang.org/unstable-book/language-features/doc-cfg.html) for `RUSTDOCFLAGS="--cfg docsrs"`

### rustfmt
In descending order of importance:

- [ ] [imports_granularity](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#imports_granularity) - love this
- [ ] [reorder_impl_items](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#reorder_impl_items) - nice standard
- [ ] [overflow_delimited_expr](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#overflow_delimited_expr) - decreases right hand drift
- [ ] [comment_width](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#comment_width)  to match the stable `max_width` of our code
- [ ] [blank_lines_upper_bound](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#blank_lines_upper_bound) - minor point, we raise it from `1` to `2`
- [ ] [inline_attribute_width](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#inline_attribute_width) less tiny lines and height in lib.rs / mod.rs

The last two are ultimately less important if it came down to it. But, unfortunately, all of these have been unstable for ages. Our [rustfmt.toml](https://github.com/kube-rs/kube-rs/blob/master/rustfmt.toml) has not changed since it landed.

For now have opened an issue on `rustfmt` to allow us to at least bail if people accidentally use stable on rustfmt (which re-orders things badly): https://github.com/rust-lang/rustfmt/issues/5022 . But that might also need to graduate (if the prs gets merged).
