### ISSUE TITLE
Protobuf Serialization Layer

### ISSUE THREAD

**Issue by clux** [kube-rs/kube-rs#725]
We hope to release a new serialization layer for kube that supports protobuf; [k8s-pb](https://github.com/kube-rs/k8s-pb).

This is an edited umbrella issue tracking progress and major outstanding work.

### Background
This is a `gold` client requirement, that will help reduce the IO overhead of large watches, but also has the potential to bring many other benefits as we bring better integration and [delineation](https://github.com/kube-rs/kube-rs/blob/master/architecture.md#crate-delineation-and-overlaps) between the serialization and api layers.

It would serve as a replacement for `k8s-openapi` if it proves viable - and it's looking like it can be. But it's still pretty early stage. See #371 and issues linked herein for further background.

### Tasks

Initial POC:
- [x] Protobuf Encoding #371 - exploration / downloads of swagger protobuf / [repo creation](https://github.com/kube-rs/k8s-pb) :tada: 
- [x] Create a codegen crate - https://github.com/kube-rs/k8s-pb/pull/5
- [x] Make library compilable - https://github.com/kube-rs/k8s-pb/pull/13
- [x] Add minimum required traits - https://github.com/kube-rs/k8s-pb/pull/14
- [x] HasSpec and HasObject traits https://github.com/kube-rs/kube-rs/issues/295 (no parallel in k8s-openapi)
- [ ] version after kubernetes version + release process https://github.com/kube-rs/k8s-pb/issues/10
- [ ] handle irregular casings issue via prost - https://github.com/kube-rs/k8s-pb/issues/2
- necessary wrappers:
  * [ ] envelope - https://github.com/kube-rs/k8s-pb/issues/6
  * [ ] `IntOrString` - https://github.com/kube-rs/k8s-pb/issues/12
  * [ ] `Time` / `Microtime` - https://github.com/kube-rs/k8s-pb/issues/7
- [ ] initial PR against kube using kube-pb

Release Readiness:
- [ ] release strategy for migrating k8s-openapi for kube-pb
- [ ] support selecting api groups to build - https://github.com/kube-rs/k8s-pb/issues/11
- [ ] optional builder patterns - https://github.com/kube-rs/k8s-pb/issues/9

Quality of life:
- [ ] case standardisation and disambiguation - https://github.com/kube-rs/k8s-pb/issues/15
- [ ] re-export types from kube to prevent lock-step dependency issues
- [ ] further generics improvements - https://github.com/kube-rs/k8s-pb/issues/4

Potential future steps:
- consider donating parts of the protobuf repo to kubernetes-client org for better relations with sigapimachinery
- find a solution for metrics API - https://github.com/kube-rs/kube-rs/issues/492
